### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by jmank88** [gochain-io/web3#13]
Run `go test` on PRs at least. Wait for #12 
Eventually, generate release binaries for #5

**Comment by r-kononov** [comment]
@treeder could you add web3 project to circle-ci (I don't have enough privileges)

**Comment by treeder** [comment]
done

**Comment by jmank88** [comment]
Looks like it's working. We can save some time and bandwidth by caching modules: https://github.com/gochain-io/gochain/blob/master/.circleci/config.yml#L18-L26
