### ISSUE TITLE
Common Contracts

### ISSUE THREAD

**Issue by jmank88** [gochain-io/web3#21]
Given contract interaction something like this:
```sh
web3 contract deploy token.sol
web3 contract list HASH # list functions
web3 contract call HASH FUNC INPUT1 INPUT2
```

Could pre-programed information about common contracts (e.g. ERC/GO-20) be used in a helpful way? Like for access without having the ABI files? Or to output a profile for a token:
```sh
web3 contract call -erc 20 0x37C93A80b5702A820CbC3050f0e9eC48a1D5e738
Name: TurboWallet Token
Token: TURBO
Total Supply: 100000000
Decimals: 18
```

**Comment by r-kononov** [comment]
@jmank88 what if we put abi files for the most popular contract types?(ie go20.abi)

**Comment by jmank88** [comment]
Can we embed them directly?

**Comment by treeder** [comment]
We could store them in this repo and they could be used for this tool, explorer, etc. Similar to the networks list.

**Comment by jmank88** [comment]
Can we embed them in the code so that the user doesn't have to bother with the abi file at all? They could use an alternate flag to indicate the interface, or even just a namespace the function e.g. `-function GO20.totalSupply`

**Comment by jmank88** [comment]
They also can just download a release and not check out the source

**Comment by treeder** [comment]
I wasn't thinking the user would download them, would be transparent to the user, just keeping a repository of common abis so multiple tools can fetch them as needed.

**Comment by r-kononov** [comment]
What if we put in the repo the most popular abis (go20 and so on) and use file embedding to put them into binary (ie go-rice or vfsgen) - that would be transparent for both users (who checkouts the code and who uses precompiled binaries),  the only downside - size of the binary would be bigger.
Thoughts?

**Comment by jmank88** [comment]
I'm not familiar with those tools specifically, but could we set up a simple command to essentially just parse the JSON via go:generate? Might be a little more light weight

**Comment by jmank88** [comment]
We can use [`abigen`](https://github.com/gochain-io/gochain/tree/master/cmd/abigen) to generate type safe go code to call instead of doing everything dynamically.
