### ISSUE TITLE
Usage enhancements before release

### ISSUE THREAD

**Issue by treeder** [gochain-io/web3#39]
Command now: 

```sh
web3 contract call --contract 0x615322405e8C099E05f2F3ec3497153CEdBbBcA7 --contract-abi HelloWorld.abi`
```

Change to:

* [x] Change `--contract` flag to `--address` 
* [x] Change `--contract-abi` flag to `--abi` or `--abi-file` (file in case we support an inline `--abi` flag?)

**Comment by jmank88** [comment]
Should consider #31 too
