### ISSUE TITLE
Called function that didn't exist and no logs in receipt

### ISSUE THREAD

**Issue by treeder** [gochain-io/web3#40]
I changed the abi to have a bad function name that didn't exist, called it, but there's nothing to indicate that it was bad.

```sh
> ./web3 contract call --contract 0x615322405e8C099E05f2F3ec3497153CEdBbBcA7 --contract-abi HelloWorld.abi --function setName2 "Johnny"
Transaction address: 0x4561a81043141f601601bdb0f376b9c6855bf64b56e42479756db83a19c2702a
> ./web3 rc 0x4561a81043141f601601bdb0f376b9c6855bf64b56e42479756db83a19c2702a
TxHash: 0x4561a81043141f601601bdb0f376b9c6855bf64b56e42479756db83a19c2702a
GasUsed: 22278
Cumulative Gas Used: 6280278
Status: 0
Post State: 0x
Bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Logs: []
```

Is there any way to know that it didn't work and shouldn't work?

**Comment by jmank88** [comment]
I'll keep digging, but this looks like normal behavior:

> The call will simply return immediately. There will be no code executed, but any value sent with the transaction will remain with the recipient contract. In fact, it will be as if you just sent ether to the contract (note that the value of the transaction can be 0). All extra data (including the ABI) will be ignored.

https://ethereum.stackexchange.com/questions/1416/what-happens-if-you-call-a-non-existent-function-of-another-contract-that-has-no

**Comment by r-kononov** [comment]
I suppose this one could be closed? @treeder ?

**Comment by treeder** [comment]
Ya, I think you just have to suffer through this, same with Ethereum.
