### ISSUE TITLE
Generated code is pretty ugly, should clean it up

### ISSUE THREAD

**Issue by treeder** [gochain-io/web3#81]
And maybe name the file `{{symbol}}.sol` instead of name.sol. 

![Screenshot 2019-03-14 at 9 40 02 AM](https://user-images.githubusercontent.com/75826/54361334-3228e100-463d-11e9-85c2-a884b75e833f.png)

**Comment by jmank88** [comment]
Should we let them choose the file name? but default to something like `<type><symbol>.sol`
