### ISSUE TITLE
Add code generation command

### ISSUE THREAD

**Issue by treeder** [gochain-io/web3#86]
```sh
web3 generate code DEMOToken.abi
```

Will run this:

```
docker run --rm -v $PWD:/contracts -w /contracts ethereum/client-go:alltools-latest abigen --abi DEMOToken.abi --pkg abi --out DEMOToken.go
sudo chown $(whoami):$(whoami) DEMOToken.go
```

Maybe we make a gochain/abigen image though so the imports generated are gochain.

I would imagine we could add support for other languages down the road too.

**Comment by jmank88** [comment]
Can we just call `package abigen` directly instead of using docker?
